export const EMPTY_STATE = 'EMPTY_STATE';
export const ADD_ELEMENT = 'ADD_ELEMENT';
export const EDIT_ELEMENT = 'EDIT_ELEMENT';
export const EDIT_ELEMENT_IGNORE = 'EDIT_ELEMENT_IGNORE';
export const SET_CURRENT_ELEMENT = 'SET_CURRENT_ELEMENT';
